// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesSystem_App.Models;

namespace SalesSystem_App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211113090646_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SalesSystem_App.Models.ClientModel", b =>
                {
                    b.Property<int>("Client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Client_fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Client_lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Client_id");

                    b.ToTable("ClientModels");
                });

            modelBuilder.Entity("SalesSystem_App.Models.OrderModel", b =>
                {
                    b.Property<int>("Order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Clients_Orders_FK1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Order_parent_id")
                        .HasColumnType("int");

                    b.Property<int?>("Sellers_Orders_FK2")
                        .HasColumnType("int");

                    b.HasKey("Order_id");

                    b.HasIndex("Clients_Orders_FK1");

                    b.HasIndex("Sellers_Orders_FK2");

                    b.ToTable("OrderModels");
                });

            modelBuilder.Entity("SalesSystem_App.Models.SellerModel", b =>
                {
                    b.Property<int>("Seller_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Seller_boss_id")
                        .HasColumnType("int");

                    b.Property<string>("Seller_fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Seller_lname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Seller_id");

                    b.ToTable("SellerModels");
                });

            modelBuilder.Entity("SalesSystem_App.Models.OrderModel", b =>
                {
                    b.HasOne("SalesSystem_App.Models.ClientModel", "Order_client_id")
                        .WithMany()
                        .HasForeignKey("Clients_Orders_FK1");

                    b.HasOne("SalesSystem_App.Models.SellerModel", "Order_seller_id")
                        .WithMany()
                        .HasForeignKey("Sellers_Orders_FK2");

                    b.Navigation("Order_client_id");

                    b.Navigation("Order_seller_id");
                });
#pragma warning restore 612, 618
        }
    }
}
